name: Sync Blog Posts to GitHub Pages
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
      
    - name: Install Dependencies
      run: |
        pip install beautifulsoup4 requests
      
    - name: Sync Blog Posts
      run: |
        python sync_blog_posts.py
      
    - name: Commit Changes
      run: |
        git config --global user.email "csq020611@gmail.com"
        git config --global user.name "cs7eric"
        git add -A
        git commit -m "Sync blog posts"
      
    - name: Push Changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.CS7ERIC_ACCESS_TOKENS }}
